version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - .env
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    env_file:
      - .env
    healthcheck:
      test: [ "CMD", "yarn", "check" ]
      interval: 30s
      timeout: 10s
      retries: 3

  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      MONGO_INITDB_DATABASE: cloth_shop
    ports:
      - "27017:27017"
    volumes:
      - ./database:/docker-entrypoint-initdb.d

volumes:
  node_modules:
  mongo_data:
